#include "gtest/gtest.h"
#include "solution.hpp"
#include <sstream>

TEST(MainTest, EndToEndTest) // a regression test
{
    std::ostringstream oss;
    std::string expected =
        " : O 1 13\n"
        " : E 2 14\n"
        "Alsóhatár utca: E 14 26\n"
        "Baross utca: O 61 61\n"
        "Baross utca: E 72 72\n"
        "Bazsarózsa utca: O 17 29\n"
        "Beregszászi utca: O 29 33\n"
        "Boglárka utca: O 3 33\n"
        "Bokréta utca: O 1 7\n"
        "Bokréta utca: E 2 10\n"
        "Budakeszi utca: O 1 5\n"
        "Budakeszi utca: E 2 4\n"
        "Bányász utca: O 49 55\n"
        "Bányász utca: E 46 52\n"
        "Esze Tamás utca: O 3 11\n"
        "Farkasréti utca: O 7 35\n"
        "Farkasréti utca: E 10 30\n"
        "Holdfény utca: E 2 12\n"
        "Kertész köz: O 1 5\n"
        "Kertész köz: E 2 8\n"
        "Kõfejtõ utca: E 2 20\n"
        "Kõhíd utca: E 2 18\n"
        "Kõkapu utca: O 1 1\n"
        "Lévai utca: O 1 35\n"
        "Lévai utca: E 34 34\n"
        "Munkácsy Mihály utca: O 1 29\n"
        "Munkácsy Mihály utca: E 2 32\n"
        "Nefelejcs utca: O 1 1\n"
        "Nefelejcs utca: O 9 17\n"
        "Nefelejcs utca: E 2 2\n"
        "Nefelejcs utca: E 22 22\n"
        "Nyár utca: O 1 3\n"
        "Nyár utca: E 2 6\n"
        "Nádasdûlõ sétány: O 1 21\n"
        "Nádasdûlõ sétány: E 10 14\n"
        "Patkó utca: O 3 7\n"
        "Petõfi Sándor utca: O 33 53\n"
        "Petõfi Sándor utca: E 34 54\n"
        "Présház utca: E 2 22\n"
        "Sport utca: E 6 6\n"
        "Szabadság út: O 53 89\n"
        "Szabadság út: O 131 145\n"
        "Szabadság út: E 48 86\n"
        "Szivárvány utca: O 1 1\n"
        "Szivárvány utca: E 12 20\n"
        "Széles utca: O 29 37\n"
        "Széles utca: E 56 78\n"
        "Tavasz utca: O 21 45\n"
        "Tavasz utca: E 2 4\n"
        "Tavasz utca: E 12 36\n"
        "Vöröshegy utca: O 19 19\n"
        "Árvácska utca: O 1 21\n"
        "Árvácska utca: E 2 16\n"
        "Építõk útja: E 2 4\n"
        "Õszibarack utca: O 33 35\n"
        "Õszibarack utca: E 26 28\n";

        solution(oss);

        EXPECT_EQ(oss.str(), expected);
}